export const cuberData = {
    f2l: [
        { id: "01", name: "Caso 01", algs: ["R U R'"] },
        { id: "02", name: "Caso 02", algs: ["y L' U' L"] },
        { id: "03", name: "Caso 03", algs: ["y U' L' U L"] },
        { id: "04", name: "Caso 04", algs: ["U R U' R'"] },
        { id: "05", name: "Caso 05", algs: ["U R U' R' U' F' U F"] },
        { id: "06", name: "Caso 06", algs: ["y U' L' U L U F U' F'"] },
        { id: "07", name: "Caso 07", algs: ["R U' R' Dw", "R' U2 R U2' R' U R"] },
        { id: "08", name: "Caso 08", algs: ["U R U R' U2 R U R'"] },
        { id: "09", name: "Caso 09", algs: ["U' R U' R' U2 R U' R'"] },
        { id: "10", name: "Caso 10", algs: ["U2 R' F R F' U2 R U R'"] },
        { id: "11", name: "Caso 11", algs: ["U' R U R' U F' U' F"] },
        { id: "12", name: "Caso 12", algs: ["R U R' U' R U R' U' R U R'"] },
        { id: "13", name: "Caso 13", algs: ["U' R' F R F' R U' R'"] },
        { id: "14", name: "Caso 14", algs: ["R U' R' U", "R U' R' U2 R U' R'"] },
        { id: "15", name: "Caso 15", algs: ["U' R U2 R' U F' U' F"] },
        { id: "16", name: "Caso 16", algs: ["U' R U' R' U R U R'"] },
        { id: "17", name: "Caso 17", algs: ["y' U R' U R U' R' U' R"] },
        { id: "18", name: "Caso 18", algs: ["R U' R' U2 F' U' F"] },
        { id: "19", name: "Caso 19", algs: ["R U R' U2 R U' R' U R U' R'"] },
        { id: "20", name: "Caso 20", algs: ["R U2 R' U' R U R'"] },
        { id: "21", name: "Caso 21", algs: ["y' R' U2 R U R' U' R"] },
        { id: "22", name: "Caso 22", algs: ["F U R U' R' F' R U' R'"] },
        { id: "23", name: "Caso 23", algs: ["R U R' U2 R U R' U' R U R'"] },
        { id: "24", name: "Caso 24", algs: ["R U R' U R U' R'"] },
        { id: "25", name: "Caso 25", algs: ["y' L' U' L U' L' U L"] },
        { id: "26", name: "Caso 26", algs: ["R U2 R' U R U' R'"] },
        { id: "27", name: "Caso 27", algs: ["y' L' U2 L U' L' U L"] },
        { id: "28", name: "Caso 28", algs: ["R U' R' U R U' R'"] },
        { id: "29", name: "Caso 29", algs: ["R U R' U' F R' F' R"] },
        { id: "30", name: "Caso 30", algs: ["R U R' U' R U R'"] },
        { id: "31", name: "Caso 31", algs: ["R' F R F' R' F R F'"] },
        { id: "32", name: "Caso 32", algs: ["R U R' U2 R U' R' U R U R'"] },
        { id: "33", name: "Caso 33", algs: ["R U R' U' R U2 R' U' R U R'"] },
        { id: "34", name: "Caso 34", algs: ["R U' R' Rw U' Rw'", "U2 Rw U Rw'"] },
        { id: "35", name: "Caso 35", algs: ["Rw U' Rw' U2", "Rw U Rw' R U R'"] },
        { id: "36", name: "Caso 36", algs: ["Dw R' U2 R U2 R' U R"] },
        { id: "37", name: "Caso 37", algs: ["U' R U2 R' U2 R U' R'"] },
        { id: "38", name: "Caso 38", algs: ["Dw R' U' R U2 R' U R"] },
        { id: "39", name: "Caso 39", algs: ["U' R U R' U2 R U' R'"] },
        { id: "40", name: "Caso 40", algs: ["U' R U R' U R U R'"] },
        { id: "41", name: "Caso 41", algs: ["U' R U' R' U F' U' F"] }
    ],
    oll: [
        { id: "01", name: "Caso 01", algs: ["R U R' U R U2 R'"] },
        { id: "02", name: "Caso 02", algs: ["R' U' R U' R' U2 R"] },
        { id: "03", name: "Caso 03", algs: ["R U R' U R U' R' U R U2 R'"] },
        { id: "04", name: "Caso 04", algs: ["R U2 R2 U' R2 U' R2 U2 R"] },
        { id: "05", name: "Caso 05", algs: ["Rw U R’ U’ Rw’ F R F’"] },
        { id: "06", name: "Caso 06", algs: ["F' Rw U R' U' Rw' F R"] },
        { id: "07", name: "Caso 07", algs: ["R2 D' R U2 R' D R U2 R"] },
        { id: "08", name: "Caso 08", algs: ["R U R' U' R' F R F'"] },
        { id: "09", name: "Caso 09", algs: ["F R U R' U' F'"] },
        { id: "10", name: "Caso 10", algs: ["Rw U2 R' U' R U' Rw'"] },
        { id: "11", name: "Caso 11", algs: ["Rw' U2 R U R' U Rw"] },
        { id: "12", name: "Caso 12", algs: ["Fw R U R' U' Fw'"] },
        { id: "13", name: "Caso 13", algs: ["Fw' L' U' L U Fw"] },
        { id: "14", name: "Caso 14", algs: ["S R U R' U' R' F R Fw'"] },
        { id: "15", name: "Caso 15", algs: ["R' U' F U R U' R' F' R"] },
        { id: "16", name: "Caso 16", algs: ["Rw U R' U' M U R U' R'"] },
        { id: "17", name: "Caso 17", algs: ["R U R' U' M' U R U' Rw'"] },
        { id: "18", name: "Caso 18", algs: ["R' U' R' F R F' U R"] },
        { id: "19", name: "Caso 19", algs: ["R U R2 U' R' F R U R U' F'"] },
        { id: "20", name: "Caso 20", algs: ["F R U' R' U' R U R' F'"] },
        { id: "21", name: "Caso 21", algs: ["R U2 R2 F R F' R U2 R'"] },
        { id: "22", name: "Caso 22", algs: ["R U R' U R' F R F' R U2 R'"] },
        { id: "23", name: "Caso 23", algs: ["R U R' U' R' F R2 U R' U' F'"] },
        { id: "24", name: "Caso 24", algs: ["Rw U R' U R U2 Rw'"] },
        { id: "25", name: "Caso 25", algs: ["Rw' U' R U' R' U2 Rw"] },
        { id: "26", name: "Caso 26", algs: ["Rw' R2 U R' U R U2 R' U M'"] },
        { id: "27", name: "Caso 27", algs: ["F R U R' U' F' U F R U R' U' F'"] },
        { id: "28", name: "Caso 28", algs: ["Rw' U' R U' R' U R U' R' U2 Rw"] },
        { id: "29", name: "Caso 29", algs: ["Rw U R' U R U' R' U R U2 Rw'"] },
        { id: "30", name: "Caso 30", algs: ["Rw U' Rw2 U Rw2 U Rw2 U' Rw"] },
        { id: "31", name: "Caso 31", algs: ["Rw' U Rw2 U' Rw2 U' Rw2 U Rw'"] },
        { id: "32", name: "Caso 32", algs: ["F' L' U' L U L' U' L U F"] },
        { id: "33", name: "Caso 33", algs: ["F R U R' U' R U R' U' F'"] },
        { id: "34", name: "Caso 34", algs: ["R U R' U R U' R' U' R' F R F'"] },
        { id: "35", name: "Caso 35", algs: ["L' U' L U' L' U L U L F' L' F"] },
        { id: "36", name: "Caso 36", algs: ["R' F R U R' F' R F U' F'"] },
        { id: "37", name: "Caso 37", algs: ["Rw U' Rw' U' Rw U Rw' F' U F"] },
        { id: "38", name: "Caso 38", algs: ["Rw' U' Rw R' U' R U Rw' U Rw"] },
        { id: "39", name: "Caso 39", algs: ["Rw U Rw' R U R' U' Rw U' Rw'"] },
        { id: "40", name: "Caso 40", algs: ["Fw R U R' U' R U R' U' Fw'"] },
        { id: "41", name: "Caso 41", algs: ["Rw U Rw' U R U' R' U R U' R' Rw U' Rw'"] },
        { id: "42", name: "Caso 42", algs: ["R U R' U R Dw' R U' R' F'"] },
        { id: "43", name: "Caso 43", algs: ["R U2 R2 U' R U' R' U2 F R F'"] },
        { id: "44", name: "Caso 44", algs: ["R' U' R U' R' U2 R F R U R' U' F'"] },
        { id: "45", name: "Caso 45", algs: ["R U R' U R U2 R' F R U R' U' F'"] },
        { id: "46", name: "Caso 46", algs: ["M U R U R' U' R' F R F' M'"] },
        { id: "47", name: "Caso 47", algs: ["F U R U2 R' U' R U2 R' U' F'"] },
        { id: "48", name: "Caso 48", algs: ["L F' L' U' L U F U' L'"] },
        { id: "49", name: "Caso 49", algs: ["R' F R U R' U' F' U R"] },
        { id: "50", name: "Caso 50", algs: ["Rw U R' U R U2 Rw2 U' R U' R' U2 Rw"] },
        { id: "51", name: "Caso 51", algs: ["M U R U R' U' M' R' F R F'"] },
        { id: "52", name: "Caso 52", algs: ["Fw R U R' U' Fw' U' F R U R' U' F'"] },
        { id: "53", name: "Caso 53", algs: ["Fw R U R' U' Fw' U F R U R' U' F'"] },
        { id: "54", name: "Caso 54", algs: ["R U2 R2' F R F' U2' R' F R F'"] },
        { id: "55", name: "Caso 55", algs: ["F R U R' U' S R U R' U' Fw'"] },
        { id: "56", name: "Caso 56", algs: ["R U R' U R' F R F' U2 R' F R F'"] },
        { id: "57", name: "Caso 57", algs: ["M U R U R' U' M2 U R U' Rw'"] }
    ],
    pll: [
        { id: "a-a-01", name: "Caso A horário", algs: ["x R' U R' D2 R U' R' D2 R2 x'"] },
        { id: "a-h-01", name: "Caso A anti-horário", algs: ["x R2' D2 R U R' D2 R U' R x'"] },
        { id: "h-01", name: "Caso H", algs: ["M2 U M2 U2 M2 U M2"] },
        { id: "z-01", name: "Caso Z", algs: ["M2 U M2 U M' U2 M2 U2 M'"] },
        { id: "t-01", name: "Caso T", algs: ["R U R' U' R' F R2 U' R' U' R U R' F'"] },
        { id: "f-01", name: "Caso F", algs: ["R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"] },
        { id: "y-01", name: "Caso Y", algs: ["F R U' R' U' R U R' F' R U R' U' R' F R F'"] },
        { id: "e-01", name: "Caso E", algs: ["x' R U' R' D R U R' D' R U R' D R U' R' D' x"] },
        { id: "v-01", name: "Caso V", algs: ["R' U R' Dw' R' F' R2 U' R' U R' F R F"] },
        { id: "r1-01", name: "Caso R1", algs: ["R U' R' U' R U R D R' U' R D' R' U2 R' U'"] },
        { id: "r2-01", name: "Caso R2", algs: ["R' U2 R U2' R' F R U R' U' R' F' R2 U'"] },
        { id: "j1-01", name: "Caso J1", algs: ["x R2 F R F' R U2 Rw' U Rw U2 x'"] },
        { id: "j2-01", name: "Caso J2", algs: ["R U R' F' R U R' U' R' F R2 U' R' U'"] },
        { id: "n1-01", name: "Caso N1", algs: ["R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"] },
        { id: "n2-01", name: "Caso N2", algs: ["R' U R U' R' F' U' F R U R' F R' F' R U' R"] },
        { id: "g1-01", name: "Caso G1", algs: ["R2' Uw R' U R' U' R Uw' R2 y' R' U R"] },
        { id: "g2-01", name: "Caso G2", algs: ["R' U' R U D' R2 U R' U R U' R U' R2 D U'"] },
        { id: "g3-01", name: "Caso G3", algs: ["R2 U' R U' R U R' U R2 D' U R U' R' D U'"] },
        { id: "g4-01", name: "Caso G4", algs: ["R U R' y' R2 Uw' R U' R' U R' Uw R2"] },
        { id: "u-a-01", name: "Caso U horário", algs: ["R' U R' U' R' U' R' U R U R2"] },
        { id: "u-h-01", name: "Caso U anti-horário", algs: ["R2 U' R' U' R U R U R U' R"] }
    ]
};

export function getImagePath(step, id) {
    const paddedId = String(id).padStart(2, '0');
    if (step === 'f2l') return `imagens/f2l/f2l-caso-${paddedId}.png`;
    if (step === 'oll') return `imagens/oll/oll-caso-${paddedId}.png`;
    if (step === 'pll') return `imagens/pll/pll-caso-${id}.png`; 
    return '';
}